services:
  postgres:
    image: postgres:13
    container_name: vehicle-access-control-db
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicle_access_control
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
